### PR TITLE
hard code spanish logo

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by smn** [comment]
my eyes!

I suspect tests are failing because of a test harness problem like I saw here: https://github.com/universalcore/unicore-cms-django/commit/2468195195ca52af35f8327a6de89b93d93c5c22

**Comment by smn** [comment]
Well, that's where I saw a similar problem anyway. New elasticsearch package has better https checking in the URLS, my typo in the test case triggered than and had ES tests fail.

**Comment by miltontony** [comment]
@smn yeah, that `http` change fixed it.
ready for review

**Comment by smn** [comment]
:+1:

**Pull request merged**
